### ISSUE TITLE
New series added to trakt list not discovered

### ISSUE THREAD

**Issue by ghost** [ianstalk/dotfiles#1]
Hi!

First, thank you very much for this config.

I´m new to flexget and I have a question with your configuration. If I launch it, it discover all the series I have in my trakt list and start downloading all perfectly. But if I add a new one to that list, the next_trakt_episodes set the first episode perfectly, but the discover does not star downloading it. It should behave like this?

Thanks!!

**Comment by ianstalk** [comment]
I'd have to look at your logs. I suggest posting your config and logs on the flexget froums (https://discuss.flexget.com/)
